Implement dockerfile
PaaavelZ/FPA-pybot pull request #13
Opened 2022-09-17 13:29 UTC by vspochernin

2022-09-17 14:17 UTC, Pobedos requested changes
https://github.com/PaaavelZ/FPA-pybot/blob/c0e143cdc153f73d8c9e0103b24f70da4a3c8502/src/config.py#L2
Можешь еще это убрать
Ну и билдер

2022-09-18 10:22 UTC, Pobedos approved these changes

2022-09-18 10:24 UTC, Pobedos commented on src/config.py
> +BACKDOOR = 123
А почему 123?) Можно было тогда уж полностью его полностью выпилить. А так пофигу

2022-09-18 10:51 UTC, vspochernin commented on src/config.py
> +BACKDOOR = 123
Удалил backdoor: f23e0d307164d8299f26108f57d17213282690ae

2022-09-18 10:53 UTC, merged