Add ability to change the word
PaaavelZ/FPA-pybot pull request #8
Opened 2022-03-04 20:49 UTC by ArtyomScheredin

2022-03-04 21:08 UTC, Pobedos requested changes

2022-03-04 21:08 UTC, Pobedos commented on Bot/main.py
> +        connect = sqlite3.connect("d:\\labs\\bot\\FPA-pybot\\Bot\\users.db")
Ток мы это деплоить будем, сомневаюсь, что там винда)

2022-03-04 21:08 UTC, Pobedos commented on Bot/main.py
> +    connect.close()
Только не в глобале

2022-03-04 21:08 UTC, Pobedos commented on Bot/config.py
> +WATERMARK1 = "••−• •• −• − •−• • −• −•• •• −• −−•fintrend" #Финтрендинг 1
мб тогда словарь лучше?

2022-03-04 21:08 UTC, Pobedos commented on Bot/main.py
> +    try:
with as

2022-03-05 06:14 UTC, PaaavelZ commented on Bot/main.py
> +        if msg.text == "Тренд":
А если сделать так:
1) Сначала создать мапу word->value;
2) Потом создать какой-нибудь сет (массив), где будут все наши кодируемые слова;
3) Тут сделать проверку на то, что слово в этом сете (массиве);
4) Если это так - то исполняем нашу команду INSERT OR REPLACE, в .format в качестве value передаём map[word];
5) ???
6) PROFIT! Слов может быть сколько угодно, код не дублируется.

2022-03-05 06:16 UTC, PaaavelZ requested changes

2022-03-05 06:16 UTC, PaaavelZ commented on Bot/main.py
> +        if msg.text == "Тренд":
А если сделать так:
1) Сначала создать мапу word->value;
2) Потом создать какой-нибудь сет (массив), где будут все наши кодируемые слова;
3) Тут сделать проверку на то, что слово в этом сете (массиве);
4) Если это так - то исполняем нашу команду INSERT OR REPLACE, в .format в качестве value передаём map[word];
5) ???
6) PROFIT! Слов может быть сколько угодно, код не дублируется.

2022-03-05 06:18 UTC, PaaavelZ commented on Bot/main.py
> +        if msg.text == "Тренд":
А если сделать так:
1) Сначала создать мапу word->value;
2) Потом создать какой-нибудь сет (массив), где будут все наши кодируемые слова;
3) Тут сделать проверку на то, что слово в этом сете (массиве);
4) Если это так - то исполняем нашу команду INSERT OR REPLACE, в .format в качестве value передаём map[word];
5) ???
6) PROFIT! Слов может быть сколько угодно, код не дублируется.

2022-03-05 06:18 UTC, PaaavelZ commented on Bot/main.py
> +        if msg.text == "Тренд":
Это на случай, если Вася будет кодировать неск слов. Пока оно не разрослось, норм

2022-03-05 06:41 UTC, merged